# vi patching.yml
---
- name: Patch Linux system
  hosts: all
  become: true
  ignore_errors: yes
  tasks:    
- name: Update Shellshock (Debian     
  yum: name=bash         
  state=latest         
  update_cache=yes    
  when: ansible_os_family == "Linux"  
- name: Update Shellshock (RedHat)    
  yum: name=bash          
 state=latest       
    update_cache=yes   
   when: ansible_os_family == "RedHat" 
    - debug: var=curl
#   - name: Start the services #Change services according to the requirement
#     service:
#       name: {{ item }}
#       state: started
#     loop:
#        - service1
#        - service2
#        - service3

#   - name: Check if the service is up 
#     shell: ps -ef | grep "service-name"
#     register: service
#   - debug: var=service 
